export const ASSIGN_USER = 'ASSIGN_USER'
export const CHANGE_MODE = 'CHANGE_MODE'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const FETCH_DATA_RECEIVE = 'FETCH_DATA_RECEIVE'
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FILTER_USERS = 'FILTER_USERS'
export const UNASSIGN_USER = 'UNASSIGN_USER'
export const USER_SELECT = 'USER_SELECT'

